### PR TITLE
README mentions license and links to LICENSE file.

### PR DESCRIPTION
**Pull request by benoitbryon**
setup.py already has "license" but LICENSE file was missing. Added it. Mentioned it in README.

Can you check license, date and copyright holder?

### CODE REVIEW

**Comment by yohanboniface** [comment]
cc @barbayellow not sure about what license BSF wants at the end.

**Comment by benoitbryon** [comment]
Added AUTHORS.md too.

**Comment by benoitbryon** [comment]
Of course, feel free to adapt the license depending on what BSF wants.
Whatever the choice, this pull-request's motivation are:
* license is visible, contributors can easily read it
* references to license are consistent, i.e. setup.py and LICENSE files

Are there references to license in debian/ folder?

**Comment by barbayellow** [comment]
@yohanboniface Clearly MIT. The content produced by BSF (videos for instance) are under CC by SA which is in our opinion the less restrictive licence. In this context, the MIT licence would make sense.

**Comment by yohanboniface** [comment]
OK :)

(CC BY SA is only for content, nor for code, AFAIK ;) ).

**Pull request merged**
